[colors.bright]
magenta = "#f5c2e7"
black = "#1e1e2e"
green = "#b8f3b1"
blue = "#74c7ec"
cyan = "#94e2d5"
red = "#eba0ac"
white = "#dfdfdf"
yellow = "#f9e2af"


[colors.normal]
black = "#181825"
blue = "#89b4fa"
cyan = "#89dceb"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#cdd6f4"
yellow = "#fab387"

[colors.primary]
background = "0x1E1E2E"
foreground = "0xD3DCFA"

[font]
size = 11.0

[font.bold_italic]
family = "jetbrainsmono nerd font"
style = "Bold Italic"

[font.italic]
family = "jetbrainsmono nerd font"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[window]
decorations = "none"
opacity = 1
