[colors.bright]
black = "#A7AAAD"
red = "#B34C31"
green = "#566FB2"
yellow = "#78844F"
blue = "#AA706E"
magenta = "#E0BB3C"
cyan = "#BEE8FF"
white = "#EEF4F7"

[colors.normal]
black = "#3C3B3B"
red = "#954530"
green = "#4C6094"
yellow = "#6D764B"
blue = "#8C605F"
magenta = "#A88C2D"
cyan = "#8FAEBF"
white = "#F9FDFF"

[colors.primary]
background = "#111010"
foreground = "#F9FDFF"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono NF"
style = "Regular"

[window]
decorations = "none"
opacity = 0.85
