[colors.bright]
black = "#23283d"
red = "#C66262"
green = "#FFC94D"
yellow = "#1EDC62"
blue = "#5C6EB1"
magenta = "#593695"
cyan = "#BEE8FF"
white = "#B9BBBE"

[colors.normal]
black = "#1e2233"
red = "#D25050"
green = "#FAA61A"
yellow = "#43B581"
blue = "#6E85D3"
magenta = "#096DC0"
cyan = "#8FAEBF"
white = "#F1F1F1"

[colors.primary]
background = "#1e2233"
foreground = "#F1F1F1"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono NF"
style = "Regular"

[window]
decorations = "none"
opacity = 0.85
